### ISSUE TITLE
make tests warning and failure on Ubuntu

### ISSUE THREAD

**Issue by Thomas-Ahn** [NetComposer/nksip#55]
While make tests, there is a Waring as:
==> nksip (eunit)
src/nksip_protocol.erl:24: Warning: behaviour nkpacket_protocol undefined

And got Error as following:
=INFO REPORT==== 24-Dec-2015::18:02:45 ===
    application: nkpacket
    exited: {bad_return,
                {{nkpacket_app,start,[normal,[]]},
                 {'EXIT',
                     {undef,
                         [{maps,get,
                              [included_applications,
                               #{connect_timeout => nat_integer,
                                 dns_cache_ttl => {integer,0,none},
                                 http_timeout => nat_integer,
                                 max_connections => {integer,1,1000000},
                                 sctp_in_streams => nat_integer,
                                 sctp_out_streams => nat_integer,
                                 sctp_timeout => nat_integer,
                                 tcp_timeout => nat_integer,
                                 tls_cacertfile => string,
                                 tls_certfile => string,
                                 tls_depth => {integer,0,16},
                                 tls_keyfile => string,
                                 tls_password => string,
                                 tls_verify => boolean,
                                 tls_versions => {list,atom},
                                 udp_timeout => nat_integer,
                                 ws_timeout => nat_integer},
                               not_found],
                              []},
                          {nklib_config,find_config,7,
                              [{file,"src/nklib_config.erl"},{line,376}]},
                          {nklib_config,parse_config,3,
                              [{file,"src/nklib_config.erl"},{line,190}]},
                          {nklib_config,load_env,3,
                              [{file,"src/nklib_config.erl"},{line,206}]},
                          {nkpacket_app,start,2,
                              [{file,"src/nkpacket_app.erl"},{line,58}]},
                          {application_master,start_it_old,4,
                              [{file,"application_master.erl"},
                               {line,272}]}]}}}}
    type: permanent
{error_logger,{{2015,12,24},{18,2,46}},"~s~n",["Error in process <0.3979.0> with exit value: {terminated,[{io,format,[<0.24.0>,\"Internal error: ~P.\n\",[{error,terminated,[{io,format,[<0.24.0>,\"~s\n\",[<<20 bytes>>]],[]},{eunit_tty,handle_cancel,3,[{file,\"eunit_tty.erl\"},{line,159}]},{eunit_listener,call,3,[{file,\"eunit_listener.erl\"},{line,131}]},{eunit_listener... \n"]}
{"Kernel pid terminated",application_controller,"{application_start_failure,nkpacket,{bad_return,{{nkpacket_app,start,[normal,[]]},{'EXIT',{undef,[{maps,get,[included_applications,#{connect_timeout => nat_integer,dns_cache_ttl => {integer,0,none},http_timeout => nat_integer,max_connections => {integer,1,1000000},sctp_in_streams => nat_integer,sctp_out_streams => nat_integer,sctp_timeout => nat_integer,tcp_timeout => nat_integer,tls_cacertfile => string,tls_certfile => string,tls_depth => {integer,0,16},tls_keyfile => string,tls_password => string,tls_verify => boolean,tls_versions => {list,atom},udp_timeout => nat_integer,ws_timeout => nat_integer},not_found],[]},{nklib_config,find_config,7,[{file,\"src/nklib_config.erl\"},{line,376}]},{nklib_config,parse_config,3,[{file,\"src/nklib_config.erl\"},{line,190}]},{nklib_config,load_env,3,[{file,\"src/nklib_config.erl\"},{line,206}]},{nkpacket_app,start,2,[{file,\"src/nkpacket_app.erl\"},{line,58}]},{application_master,start_it_old,4,[{file,\"application_master.erl\"},{line,272}]}]}}}}}"}

Crash dump was written to: erl_crash.dump
Kernel pid terminated (application_controller) ({application_start_failure,nkpacket,{bad_return,{{nkpacket_app,start,[normal,[]]},{'EXIT',{undef,[{maps,get,[included_applications,#{connect_timeout =
make: *** [eunit] Error 1

**Comment by kalta** [comment]
It seems you are using an old Erlang version, without maps support. NkSIP needs Erlang 17 (int is not tested in 18).

**Comment by Thomas-Ahn** [comment]
Erlang latest version downloaded and compiled at my server and I'm uising Erlang 17.
root@playout:~# erl
Erlang/OTP 17 [erts-6.0] [source] [64-bit] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V6.0  (abort with ^G)

**Comment by Thomas-Ahn** [comment]
After upgrade to Erlang 17.5, now it is okay..
