### ISSUE TITLE
make tests on centos6.4 failed,and I don't know why the port 5060 is in use. ( I use 'netstat -ano|grep 5060' to view before the test).

### ISSUE THREAD

**Issue by rookiephp** [NetComposer/nksip#59]
test/torture1_test.erl:34:<0.3982.0>: Starting torture1_test
test/refer_test.erl:66:<0.3982.0>: Starting refer_test
10:17:16.630 [notice] gen_tcp port 5060 is in use, waiting (5)
10:17:17.631 [notice] gen_tcp port 5060 is in use, waiting (4)
10:17:18.632 [notice] gen_tcp port 5060 is in use, waiting (3)
10:17:19.633 [notice] gen_tcp port 5060 is in use, waiting (2)
10:17:20.634 [notice] gen_tcp port 5060 is in use, waiting (1)
10:17:21.635 [error] could not start tcp transport on {0,0,0,0}:5060 (eaddrinuse)
10:17:21.635 [warning] UDP transport could not open TCP port 5060: eaddrinuse
10:17:21.635 [error] could not start UDP transport on {0,0,0,0}:0 (could_not_open_tcp)
module 'path_test'
*** context setup failed ***
**in function tests_util:start/3 (test/tests_util.erl, line 46)
in call from path_test:start/0 (test/path_test.erl, line 66)
**error:{badmatch,
    {error,
        {{shutdown,
             {failed_to_start_child,transports,
                 {could_not_start,{udp,could_not_open_tcp}}}},
         {child,undefined,bjtrl8g,
             {nkservice_service_sup,start_link,
                 [#{cache => #{log_level => 6},
                    callback => path_test,
                    class => nksip,
                    id => bjtrl8g,
                    log_level => 6,...}]},
             permanent,infinity,supervisor,
             [nkservice_service_sup]}}}}

10:17:21.845 [notice] gen_tcp port 5060 is in use, waiting (5)
10:17:22.846 [notice] gen_tcp port 5060 is in use, waiting (4)
10:17:23.847 [notice] gen_tcp port 5060 is in use, waiting (3)
10:17:24.848 [notice] gen_tcp port 5060 is in use, waiting (2)
10:17:25.849 [notice] gen_tcp port 5060 is in use, waiting (1)
10:17:26.850 [error] could not start tcp transport on {0,0,0,0}:5060 (eaddrinuse)
10:17:26.850 [warning] UDP transport could not open TCP port 5060: eaddrinuse
10:17:26.850 [error] could not start UDP transport on {0,0,0,0}:5060 (could_not_open_tcp)
module 'invite_test'
*** context setup failed ***
**in function tests_util:start/3 (test/tests_util.erl, line 46)
in call from invite_test:start/0 (test/invite_test.erl, line 48)
**error:{badmatch,
    {error,
        {{shutdown,
             {failed_to_start_child,transports,
                 {could_not_start,{udp,could_not_open_tcp}}}},
         {child,undefined,b3finlv,
             {nkservice_service_sup,start_link,
                 [#{cache => #{log_level => 6},
                    callback => invite_test,
                    class => nksip,
                    id => b3finlv,
                    log_level => 6,...}]},
             permanent,infinity,supervisor,
             [nkservice_service_sup]}}}}

module 'outbound_test'
*** context setup failed ***
**in function tests_util:start/3 (test/tests_util.erl, line 46)
in call from outbound_test:start/0 (test/outbound_test.erl, line 50)
**error:{badmatch,{error,already_started}}

10:17:27.055 [notice] gen_tcp port 5060 is in use, waiting (5)
10:17:28.056 [notice] gen_tcp port 5060 is in use, waiting (4)
10:17:29.057 [notice] gen_tcp port 5060 is in use, waiting (3)
10:17:30.058 [notice] gen_tcp port 5060 is in use, waiting (2)
10:17:31.059 [notice] gen_tcp port 5060 is in use, waiting (1)
10:17:32.060 [error] could not start tcp transport on {0,0,0,0}:5060 (eaddrinuse)
10:17:32.060 [warning] UDP transport could not open TCP port 5060: eaddrinuse
10:17:32.060 [error] could not start UDP transport on {0,0,0,0}:5060 (could_not_open_tcp)
module 'gruu_test'
*** context setup failed ***
**in function tests_util:start/3 (test/tests_util.erl, line 46)
in call from gruu_test:start/0 (test/gruu_test.erl, line 45)
**error:{badmatch,
    {error,
        {{shutdown,
             {failed_to_start_child,transports,
                 {could_not_start,{udp,could_not_open_tcp}}}},
         {child,undefined,a2ucfiu,
             {nkservice_service_sup,start_link,
                 [#{cache => #{log_level => 6},
                    callback => gruu_test,
                    class => nksip,
                    id => a2ucfiu,
                    log_level => 6,...}]},
             permanent,infinity,supervisor,
             [nkservice_service_sup]}}}}

10:17:32.312 [notice] gen_tcp port 5060 is in use, waiting (5)
10:17:33.313 [notice] gen_tcp port 5060 is in use, waiting (4)
10:17:34.314 [notice] gen_tcp port 5060 is in use, waiting (3)
10:17:35.315 [notice] gen_tcp port 5060 is in use, waiting (2)
10:17:36.316 [notice] gen_tcp port 5060 is in use, waiting (1)
10:17:37.317 [error] could not start tcp transport on {0,0,0,0}:5060 (eaddrinuse)
10:17:37.317 [warning] UDP transport could not open TCP port 5060: eaddrinuse
10:17:37.317 [error] could not start UDP transport on {0,0,0,0}:5060 (could_not_open_tcp)
module 'publish_test'
*** context setup failed ***
**in function tests_util:start/3 (test/tests_util.erl, line 46)
in call from publish_test:start/0 (test/publish_test.erl, line 44)
**error:{badmatch,
    {error,
        {{shutdown,
             {failed_to_start_child,transports,
                 {could_not_start,{udp,could_not_open_tcp}}}},
         {child,undefined,b3finlv,
             {nkservice_service_sup,start_link,
                 [#{cache => #{log_level => 6},
                    callback => publish_test,
                    class => nksip,
                    id => b3finlv,
                    log_level => 6,...}]},
             permanent,infinity,supervisor,
             [nkservice_service_sup]}}}}

10:17:37.574 [notice] gen_tcp port 5060 is in use, waiting (5)
10:17:38.575 [notice] gen_tcp port 5060 is in use, waiting (4)
10:17:39.576 [notice] gen_tcp port 5060 is in use, waiting (3)
10:17:40.577 [notice] gen_tcp port 5060 is in use, waiting (2)
10:17:41.578 [notice] gen_tcp port 5060 is in use, waiting (1)
10:17:42.579 [error] could not start tcp transport on {0,0,0,0}:5060 (eaddrinuse)
10:17:42.579 [warning] UDP transport could not open TCP port 5060: eaddrinuse
10:17:42.579 [error] could not start UDP transport on {0,0,0,0}:5060 (could_not_open_tcp)
module 'prack_test'
*** context setup failed ***
**in function tests_util:start/3 (test/tests_util.erl, line 46)
in call from prack_test:start/0 (test/prack_test.erl, line 51)
**error:{badmatch,
    {error,
        {{shutdown,
             {failed_to_start_child,transports,
                 {could_not_start,{udp,could_not_open_tcp}}}},
         {child,undefined,b3finlv,
             {nkservice_service_sup,start_link,
                 [#{cache => #{log_level => 6},
                    callback => prack_test,
                    class => nksip,
                    id => b3finlv,
                    log_level => 6,...}]},
             permanent,infinity,supervisor,
             [nkservice_service_sup]}}}}

10:17:42.742 [notice] gen_tcp port 5060 is in use, waiting (5)
10:17:43.743 [notice] gen_tcp port 5060 is in use, waiting (4)
10:17:44.744 [notice] gen_tcp port 5060 is in use, waiting (3)
10:17:45.745 [notice] gen_tcp port 5060 is in use, waiting (2)
10:17:46.746 [notice] gen_tcp port 5060 is in use, waiting (1)
10:17:47.747 [error] could not start tcp transport on {0,0,0,0}:5060 (eaddrinuse)
10:17:47.747 [warning] UDP transport could not open TCP port 5060: eaddrinuse
10:17:47.747 [error] could not start UDP transport on {0,0,0,0}:5060 (could_not_open_tcp)
module 'uas_test'
*** context setup failed ***
**in function tests_util:start/3 (test/tests_util.erl, line 46)
in call from uas_test:start/0 (test/uas_test.erl, line 47)
**error:{badmatch,
    {error,
        {{shutdown,
             {failed_to_start_child,transports,
                 {could_not_start,{udp,could_not_open_tcp}}}},
         {child,undefined,a2ucfiu,
             {nkservice_service_sup,start_link,
                 [#{cache => #{log_level => 6},
                    callback => uas_test,
                    class => nksip,
                    id => a2ucfiu,
                    log_level => 6,...}]},
             permanent,infinity,supervisor,
             [nkservice_service_sup]}}}}

10:17:48.862 [notice] gen_tcp port 5060 is in use, waiting (5)
10:17:49.863 [notice] gen_tcp port 5060 is in use, waiting (4)
10:17:50.864 [notice] gen_tcp port 5060 is in use, waiting (3)
10:17:51.865 [notice] gen_tcp port 5060 is in use, waiting (2)
10:17:52.866 [notice] gen_tcp port 5060 is in use, waiting (1)
10:17:53.867 [error] could not start tcp transport on {0,0,0,0}:5060 (eaddrinuse)
10:17:53.867 [warning] UDP transport could not open TCP port 5060: eaddrinuse
10:17:53.867 [error] could not start UDP transport on {0,0,0,0}:0 (could_not_open_tcp)
module 'basic_test'
*** context setup failed ***
**in function tests_util:start/3 (test/tests_util.erl, line 46)
in call from basic_test:start/0 (test/basic_test.erl, line 76)
**error:{badmatch,
    {error,
        {{shutdown,
             {failed_to_start_child,transports,
                 {could_not_start,{udp,could_not_open_tcp}}}},
         {child,undefined,ayr8ncm,
             {nkservice_service_sup,start_link,
                 [#{arg => client2,
                    cache => #{log_level => 6},
                    callback => basic_test,
                    class => nksip,
                    id => ayr8ncm,...}]},
             permanent,infinity,supervisor,
             [nkservice_service_sup]}}}}

module 'ipv6_test'
*** context setup failed ***
**in function tests_util:start/3 (test/tests_util.erl, line 46)
in call from ipv6_test:start/0 (test/ipv6_test.erl, line 65)
**error:{badmatch,{error,already_started}}

module 'basic2_test'
*** context setup failed ***
**in function tests_util:start/3 (test/tests_util.erl, line 46)
in call from basic2_test:start/0 (test/basic2_test.erl, line 46)
**error:{badmatch,{error,already_started}}

undefined
*** context setup failed ***
**in function tests_util:start/3 (test/tests_util.erl, line 46)
in call from proxy_test:start/1 (test/proxy_test.erl, line 74)
in call from proxy_test:'-stateless_test_/0-fun-0-'/0 (test/proxy_test.erl, line 35)
**error:{badmatch,{error,already_started}}

undefined
*** context setup failed ***
**in function tests_util:start/3 (test/tests_util.erl, line 46)
in call from proxy_test:start/1 (test/proxy_test.erl, line 74)
in call from proxy_test:'-stateful_test_/0-fun-0-'/0 (test/proxy_test.erl, line 54)
**error:{badmatch,{error,already_started}}

module 'register_test'
*** context setup failed ***
**in function tests_util:start/3 (test/tests_util.erl, line 46)
in call from register_test:start/0 (test/register_test.erl, line 48)
**error:{badmatch,{error,already_started}}

module 'uac_test'
*** context setup failed ***
**in function tests_util:start/3 (test/tests_util.erl, line 46)
in call from uac_test:start/0 (test/uac_test.erl, line 47)
**error:{badmatch,{error,already_started}}

module 'websocket_test'
*** context setup failed ***
**in function tests_util:start/3 (test/tests_util.erl, line 46)
in call from websocket_test:start/0 (test/websocket_test.erl, line 64)
**error:{badmatch,{error,already_started}}

module 'torture2_test'
*** context setup failed ***
**in function tests_util:start/3 (test/tests_util.erl, line 46)
in call from torture2_test:start/0 (test/torture2_test.erl, line 64)
**error:{badmatch,{error,already_started}}

module 'update_test'
*** context setup failed ***
**in function tests_util:start/3 (test/tests_util.erl, line 46)
in call from update_test:start/0 (test/update_test.erl, line 44)
**error:{badmatch,{error,already_started}}

test/sctp_test.erl:44:<0.3982.0>: Skipping SCTP test (no Erlang support)
test/sctp_test.erl:44:<0.3982.0>: Skipping SCTP test (no Erlang support)
10:17:54.944 [notice] gen_tcp port 5060 is in use, waiting (5)
10:17:55.945 [notice] gen_tcp port 5060 is in use, waiting (4)
10:17:56.946 [notice] gen_tcp port 5060 is in use, waiting (3)
10:17:57.947 [notice] gen_tcp port 5060 is in use, waiting (2)
10:17:58.948 [notice] gen_tcp port 5060 is in use, waiting (1)
10:17:59.949 [error] could not start tcp transport on {0,0,0,0}:5060 (eaddrinuse)
10:17:59.949 [warning] UDP transport could not open TCP port 5060: eaddrinuse
10:17:59.949 [error] could not start UDP transport on {0,0,0,0}:5060 (could_not_open_tcp)
module 'timer_test'
*** context setup failed ***
**in function tests_util:start/3 (test/tests_util.erl, line 46)
in call from timer_test:start/0 (test/timer_test.erl, line 43)
**error:{badmatch,
    {error,
        {{shutdown,
             {failed_to_start_child,transports,
                 {could_not_start,{udp,could_not_open_tcp}}}},
         {child,undefined,bwrqsly,
             {nkservice_service_sup,start_link,
                 [#{cache => #{log_level => 6},
                    callback => timer_test,
                    class => nksip,
                    id => bwrqsly,
                    log_level => 6,...}]},
             permanent,infinity,supervisor,
             [nkservice_service_sup]}}}}

10:18:00.247 [notice] gen_tcp port 5060 is in use, waiting (5)
10:18:01.248 [notice] gen_tcp port 5060 is in use, waiting (4)
10:18:02.249 [notice] gen_tcp port 5060 is in use, waiting (3)
10:18:03.250 [notice] gen_tcp port 5060 is in use, waiting (2)
10:18:04.251 [notice] gen_tcp port 5060 is in use, waiting (1)
10:18:05.252 [error] could not start tcp transport on {0,0,0,0}:5060 (eaddrinuse)
10:18:05.252 [warning] UDP transport could not open TCP port 5060: eaddrinuse
10:18:05.252 [error] could not start UDP transport on {0,0,0,0}:5060 (could_not_open_tcp)
module 'fork_test'
*** context setup failed ***
**in function fork_test:start/0 (test/fork_test.erl, line 51)
**error:{badmatch,
    {error,
        {{shutdown,
             {failed_to_start_child,transports,
                 {could_not_start,{udp,could_not_open_tcp}}}},
         {child,undefined,b0qvimk,
             {nkservice_service_sup,start_link,
                 [#{cache => #{log_level => 6},
                    callback => fork_test,
                    class => nksip,
                    id => b0qvimk,
                    log_level => 6,...}]},
             permanent,infinity,supervisor,
             [nkservice_service_sup]}}}}

module 'event_test'
*** context setup failed ***
**in function tests_util:start/3 (test/tests_util.erl, line 46)
in call from event_test:start/0 (test/event_test.erl, line 48)
**error:{badmatch,{error,already_started}}

module 'torture3_test'
*** context setup failed ***
**in function tests_util:start/3 (test/tests_util.erl, line 46)
in call from torture3_test:start/0 (test/torture3_test.erl, line 62)
**error:{badmatch,{error,already_started}}

module 'auth_test'
*** context setup failed ***
**in function tests_util:start/3 (test/tests_util.erl, line 46)
in call from auth_test:start/0 (test/auth_test.erl, line 45)
**error:{badmatch,{error,already_started}}

=======================================================
  Failed: 0.  Skipped: 0.  Passed: 24.
One or more tests were cancelled.
Cover analysis: /opt/nksip/.eunit/index.html
Coverdata export: /opt/nksip/.eunit/eunit.coverdata

=INFO REPORT==== 28-Mar-2016::10:18:24 ===
    application: gun
    exited: stopped
    type: permanent
10:18:24.370 [error] Module nkpacket_util received unexpected listen_handle_info: [{'EXIT',<0.4068.0>,shutdown},{nkport,{nksip,b3finlv},nksip_protocol,udp,{0,0,0,0},5070,undefined,undefined,{0,0,0,0},5070,<0.5712.0>,#Port<0.157746>,#{}}]
10:18:24.370 [error] Module nkpacket_util received unexpected listen_handle_info: [{'EXIT',<0.4068.0>,shutdown},{nkport,{nksip,a2ucfiu},nksip_protocol,tcp,{0,0,0,0},5060,undefined,undefined,{0,0,0,0},5060,<0.5588.0>,#Port<0.156263>,#{}}]
10:18:24.370 [error] Module nkpacket_util received unexpected listen_handle_info: [{'EXIT',<0.4068.0>,shutdown},{nkport,{nksip,a2ucfiu},nksip_protocol,udp,{0,0,0,0},5060,undefined,undefined,{0,0,0,0},5060,<0.5587.0>,#Port<0.156262>,#{}}]
10:18:24.370 [notice] Module nkservice_callbacks received unexpected info {'EXIT',<0.4068.0>,shutdown}
10:18:24.370 [error] Module nkpacket_util received unexpected listen_handle_info: [{'EXIT',<0.4068.0>,shutdown},{nkport,{nksip,b3finlv},nksip_protocol,tcp,{0,0,0,0},5070,undefined,undefined,{0,0,0,0},5070,<0.5713.0>,#Port<0.157747>,#{}}]

=ERROR REPORT==== 28-Mar-2016::10:18:24 ===
** Generic server b3finlv terminating 
** Last message in was {'EXIT',<0.4068.0>,shutdown}
** When Server state == {state,b3finlv,#{id => b3finlv,my_name => client1}}
** Reason for termination == 
** {function_clause,
       [{basic_test,handle_info,
            [{'EXIT',<0.4068.0>,shutdown},#{id => b3finlv,my_name => client1}],
            [{file,"test/basic_test.erl"},{line,289}]},
        {b3finlv,handle_info,2,[]},
        {nklib_gen_server,handle_info,4,
            [{file,"src/nklib_gen_server.erl"},{line,108}]},
        {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,593}]},
        {gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,659}]},
        {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}
10:18:24.370 [error] Module nkpacket_util received unexpected listen_handle_info: [{'EXIT',<0.4068.0>,shutdown},{nkport,{nksip,afrj6f1},nksip_protocol,ws,{0,0,0,0},8090,undefined,undefined,{0,0,0,0},8090,<0.5960.0>,<0.5961.0>,#{ws_proto => <<"sip">>}}]
10:18:24.370 [warning] Module nkpacket_cowboy received unexpected info: {'EXIT',<0.4068.0>,shutdown}
10:18:24.370 [warning] Module nkpacket_cowboy received unexpected info: {'EXIT',<0.4068.0>,shutdown}
10:18:24.370 [error] Module nkpacket_util received unexpected listen_handle_info: [{'EXIT',<0.4068.0>,shutdown},{nkport,{nksip,afrj6f1},nksip_protocol,wss,{0,0,0,0},8091,undefined,undefined,{0,0,0,0},8091,<0.6065.0>,<0.6066.0>,#{ws_proto => <<"sip">>}}]
10:18:24.370 [warning] Module nkpacket_cowboy received unexpected info: {'EXIT',<0.4068.0>,shutdown}
10:18:24.370 [error] Module nkpacket_util received unexpected listen_handle_info: [{'EXIT',<0.4068.0>,shutdown},{nkport,{nksip,afrj6f1},nksip_protocol,ws,{0,0,0,0},32781,undefined,undefined,{0,0,0,0},32781,<0.6171.0>,<0.6172.0>,#{path => <<"/ws">>,ws_proto => <<"sip">>}}]
10:18:24.370 [warning] Module nkpacket_cowboy received unexpected info: {'EXIT',<0.4068.0>,shutdown}
10:18:24.370 [notice] Module nkservice_callbacks received unexpected info {'EXIT',<0.4068.0>,shutdown}
10:18:24.370 [error] Module nkpacket_util received unexpected listen_handle_info: [{'EXIT',<0.4068.0>,shutdown},{nkport,{nksip,ax81sua},nksip_protocol,wss,{0,0,0,0},8092,undefined,undefined,{0,0,0,0},8092,<0.6282.0>,<0.6283.0>,#{path => <<"/ws">>,ws_proto => <<"sip">>}}]
10:18:24.370 [error] Module nkpacket_util received unexpected listen_handle_info: [{'EXIT',<0.4068.0>,shutdown},{nkport,{nksip,ax81sua},nksip_protocol,ws,{0,0,0,0},8090,undefined,undefined,{0,0,0,0},8090,<0.6281.0>,<0.5961.0>,#{ws_proto => <<"sip">>}}]
10:18:24.370 [error] Module nkpacket_util received unexpected listen_handle_info: [{'EXIT',<0.4068.0>,shutdown},{nkport,{nksip,a2ucfiu},nksip_protocol,tls,{0,0,0,0},5061,undefined,undefined,{0,0,0,0},5061,<0.5602.0>,{sslsocket,nil,{#Port<0.156264>,{config,{ssl_options,tls,[{3,3},{3,2},{3,1}],verify_none,{#Fun<ssl.7.125280099>,[]},#Fun<ssl.8.125280099>,false,false,undefined,1,<<"/opt/nksip/deps/nkpacket/priv/cert.pem">>,undefined,<<"/opt/nksip/deps/nkpacket/priv/key.pem">>,undefined,[],undefined,<<>>,undefined,undefined,undefined,undefined,undefined,[<<"ﾤ">>,<<"ﾨ">>,<<"ﾦ">>,<<"ﾪ">>,<<0,107>>,<<0,106>>,<<0,61>>,<<"ﾣ">>,<<"ﾧ">>,<<"ﾥ">>,<<"ﾩ">>,<<0,103>>,<<0,64>>,<<0,60>>,<<"ￜn">>,<<192,20>>,<<0,57>>,<<0,56>>,<<192,5>>,<<192,15>>,<<0,53>>,<<"ￜb">>,<<192,18>>,<<0,22>>,<<0,19>>,<<192,3>>,<<"ￜr">>,<<0,10>>,<<"ￜt">>,<<192,19>>,<<0,51>>,<<0,50>>,<<192,4>>,<<192,14>>,<<0,47>>,<<192,7>>,<<192,17>>,<<0,5>>,<<0,4>>,<<0,21>>,<<192,2>>,<<"ￜf">>,<<0,9>>],#Fun<ssl.1.125280099>,true,268435456,false,undefined,false,undefined,undefined,true,undefined,false,true,false},[{packet,raw},{ip,{0,0,0,0}},{active,once},{mode,binary},{nodelay,true},{keepalive,true},{reuseaddr,true},{backlog,1024}],<0.5603.0>,[{backlog,1024},{reuseaddr,true},{keepalive,true},{nodelay,true},{ip,{0,0,0,0}},{packet_size,0},{packet,0},{header,0},{active,false},{mode,binary}],{gen_tcp,tcp,tcp_closed,tcp_error},tls_connection}}},#{}}]
10:18:24.371 [error] Module nkpacket_util received unexpected listen_handle_info: [{'EXIT',<0.4068.0>,shutdown},{nkport,{nksip,b3finlv},nksip_protocol,tls,{0,0,0,0},5071,undefined,undefined,{0,0,0,0},5071,<0.5817.0>,{sslsocket,nil,{#Port<0.157748>,{config,{ssl_options,tls,[{3,3},{3,2},{3,1}],verify_none,{#Fun<ssl.7.125280099>,[]},#Fun<ssl.8.125280099>,false,false,undefined,1,<<"/opt/nksip/deps/nkpacket/priv/cert.pem">>,undefined,<<"/opt/nksip/deps/nkpacket/priv/key.pem">>,undefined,[],undefined,<<>>,undefined,undefined,undefined,undefined,undefined,[<<"ﾤ">>,<<"ﾨ">>,<<"ﾦ">>,<<"ﾪ">>,<<0,107>>,<<0,106>>,<<0,61>>,<<"ﾣ">>,<<"ﾧ">>,<<"ﾥ">>,<<"ﾩ">>,<<0,103>>,<<0,64>>,<<0,60>>,<<"ￜn">>,<<192,20>>,<<0,57>>,<<0,56>>,<<192,5>>,<<192,15>>,<<0,53>>,<<"ￜb">>,<<192,18>>,<<0,22>>,<<0,19>>,<<192,3>>,<<"ￜr">>,<<0,10>>,<<"ￜt">>,<<192,19>>,<<0,51>>,<<0,50>>,<<192,4>>,<<192,14>>,<<0,47>>,<<192,7>>,<<192,17>>,<<0,5>>,<<0,4>>,<<0,21>>,<<192,2>>,<<"ￜf">>,<<0,9>>],#Fun<ssl.1.125280099>,true,268435456,false,undefined,false,undefined,undefined,true,undefined,false,true,false},[{packet,raw},{ip,{0,0,0,0}},{active,once},{mode,binary},{nodelay,true},{keepalive,true},{reuseaddr,true},{backlog,1024}],<0.5818.0>,[{backlog,1024},{reuseaddr,true},{keepalive,true},{nodelay,true},{ip,{0,0,0,0}},{packet_size,0},{packet,0},{header,0},{active,false},{mode,binary}],{gen_tcp,tcp,tcp_closed,tcp_error},tls_connection}}},#{}}]

=INFO REPORT==== 28-Mar-2016::10:18:24 ===
    application: nklib
    exited: stopped
    type: permanent
10:18:24.399 [warning] Exception calling nksip_registrar:plugin_stop: error:undef
[{undefined,nks_sip_debug,[undefined,undefined,{error,"Error calling callback ~p/~p: ~p",[sip_registrar_store,2,{badarg,[{ets,safe_fixtable,[nklib_store,true],[]},{ets,foldl,3,[{file,"ets.erl"},{line,526}]},{nksip_callbacks,nks_sip_call,3,[{file,"src/nksip_callbacks.erl"},{line,243}]},{nksip_registrar_lib,callback,2,[{file,"src/nksip_registrar_lib.erl"},{line,417}]},{nksip_registrar,clear,1,[{file,"src/nksip_registrar.erl"},{line,231}]},{nksip_registrar,plugin_stop,1,[{file,"src/nksip_registrar.erl"},{line,84}]},{nkservice_util,safe_call,3,[{file,"src/nkservice_util.erl"},{line,74}]},{nkservice_server,do_stop_plugins,2,[{file,"src/nkservice_server.erl"},{line,475}]}]}]}],[]},{nksip_callbacks,nks_sip_call,3,[{file,"src/nksip_callbacks.erl"},{line,245}]},{nksip_registrar_lib,callback,2,[{file,"src/nksip_registrar_lib.erl"},{line,417}]},{nksip_registrar,clear,1,[{file,"src/nksip_registrar.erl"},{line,231}]},{nksip_registrar,plugin_stop,1,[{file,"src/nksip_registrar.erl"},{line,84}]},{nkservice_util,safe_call,3,[{file,"src/nkservice_util.erl"},{line,74}]},{nkservice_server,do_stop_plugins,2,[{file,"src/nkservice_server.erl"},{line,475}]},{nkservice_server,terminate,2,[{file,"src/nkservice_server.erl"},{line,414}]}]

=ERROR REPORT==== 28-Mar-2016::10:18:24 ===
** Generic server a2ucfiu terminating 
** Last message in was {'EXIT',<0.4068.0>,shutdown}
** When Server state == {state,a2ucfiu,#{id => a2ucfiu,my_name => server1}}
** Reason for termination == 
** {function_clause,
       [{basic_test,handle_info,
            [{'EXIT',<0.4068.0>,shutdown},#{id => a2ucfiu,my_name => server1}],
            [{file,"test/basic_test.erl"},{line,289}]},
        {a2ucfiu,handle_info,2,[]},
        {nklib_gen_server,handle_info,4,
            [{file,"src/nklib_gen_server.erl"},{line,108}]},
        {gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,593}]},
        {gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,659}]},
        {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}

=INFO REPORT==== 28-Mar-2016::10:18:24 ===
    application: goldrush
    exited: stopped
    type: permanent

=INFO REPORT==== 28-Mar-2016::10:18:24 ===
    application: ranch
    exited: stopped
    type: permanent

=INFO REPORT==== 28-Mar-2016::10:18:24 ===
    application: nksip
    exited: stopped
    type: permanent

=INFO REPORT==== 28-Mar-2016::10:18:24 ===
    application: nkservice
    exited: stopped
    type: permanent

=INFO REPORT==== 28-Mar-2016::10:18:24 ===
    application: cowlib
    exited: stopped
    type: permanent

=INFO REPORT==== 28-Mar-2016::10:18:24 ===
    application: asn1
    exited: stopped
    type: permanent

=INFO REPORT==== 28-Mar-2016::10:18:24 ===
    application: public_key
    exited: stopped
    type: permanent

=INFO REPORT==== 28-Mar-2016::10:18:24 ===
    application: ssh
    exited: stopped
    type: permanent

=INFO REPORT==== 28-Mar-2016::10:18:24 ===
    application: lager
    exited: stopped
    type: permanent

=INFO REPORT==== 28-Mar-2016::10:18:24 ===
    application: syntax_tools
    exited: stopped
    type: permanent

=INFO REPORT==== 28-Mar-2016::10:18:24 ===
    application: cowboy
    exited: stopped
    type: permanent

=INFO REPORT==== 28-Mar-2016::10:18:24 ===
    application: compiler
    exited: stopped
    type: permanent

=INFO REPORT==== 28-Mar-2016::10:18:24 ===
    application: nkpacket
    exited: stopped
    type: permanent

=INFO REPORT==== 28-Mar-2016::10:18:24 ===
    application: ssl
    exited: stopped
    type: permanent

=INFO REPORT==== 28-Mar-2016::10:18:24 ===
    application: sasl
    exited: stopped
    type: permanent
ERROR: One or more eunit tests failed.
ERROR: eunit failed while processing /opt/nksip: rebar_abort
make: *** [eunit] 错误 1

**Comment by own-star** [comment]
Hi.
I have the same error (debian 8, ubuntu 12.04.5 LTS, CentOS release 5.9 ).
How to fix it?

**Comment by kalta** [comment]
Did you do make tests?
Make sure no service is listening on 5060, udp and tcp

**Comment by own-star** [comment]
When I do make tests
I can see
...
test/torture2_test.erl:70:<0.1906.0>: Starting torture2_test
10:39:00.585 [notice] gen_tcp port 5060 is in use, waiting (5)
10:39:01.586 [notice] gen_tcp port 5060 is in use, waiting (4)
10:39:02.587 [notice] gen_tcp port 5060 is in use, waiting (3)
10:39:03.588 [notice] gen_tcp port 5060 is in use, waiting (2)
10:39:04.589 [notice] gen_tcp port 5060 is in use, waiting (1)
10:39:05.590 [error] could not start tcp transport on {0,0,0,0}:5060 (eaddrinuse)
10:39:05.590 [warning] UDP transport could not open TCP port 5060: eaddrinuse
10:39:05.590 [error] could not start UDP transport on {0,0,0,0}:0 (could_not_open_tcp)
module 'uas_test'
...

netstat -lpn
...
tcp        0      0 0.0.0.0:5060            0.0.0.0:*               LISTEN      7703/beam.smp   
tcp        0      0 0.0.0.0:5061            0.0.0.0:*               LISTEN      7703/beam.smp 
...
udp        0      0 0.0.0.0:5060            0.0.0.0:*                           7703/beam.smp   
udp        0      0 0.0.0.0:5060            0.0.0.0:*                           7703/beam.smp   
udp        0      0 0.0.0.0:5070            0.0.0.0:*                           7703/beam.smp   
...

the process 7703 it's make tests
