### ISSUE TITLE
nksip:update/2 doesn't work

### ISSUE THREAD

**Issue by own-star** [NetComposer/nksip#62]
when I start 
$make shell
then 
nksip:start(server, #{sip_local_host => "172.21.252.31", sip_from => "sip:172.21.252.31", plugins => [nksip_uac_auto_auth, nksip_uac_auto_register, nksip_registrar, nksip_100rel], transports => "sip:172.21.252.31:5060"}).

after that in the other console I change src/nksip_callbacks.erl
$make

In previous console 
nksip:update(server, []).
But callback functions don't change.

Is it normal?

**Comment by kalta** [comment]
I don't understand the scenario you are using. 
Why do you have two consoles?
What do you mean woth "callback functions don't change"?

**Comment by own-star** [comment]
I initiate two sessions with ssh
at first console: $ ssh 172.21.252.31 
and at second:  $ ssh 172.21.252.31

at first: $make shell
and server starts

at second: $ vim src/nksip_callbacks.erl
and change function **sip_route** for example
then compile
$make

I do **nksip:update(server, []).** at first console. I expect that new code will runб without restarting shell.

**Comment by kalta** [comment]
Well, you have to recompile nksip_callbacks.erl for that to work. NkSIP will never recompile source files by itself.

In fact, if you are changing a existing function, and not adding or removing functions or plugins, you don't need to do the update. 

However, It does not seem like a good practice to change nksip_callbacks.erl. The whole idea of the plugin mechanism is that you can change the behaviour without touching the existing code. Use your own callback module!
