### ISSUE TITLE
nksip as proxy for webrtc will route

### ISSUE THREAD

**Issue by matlab2000** [NetComposer/nksip#63]
there are two webrtc clients ，nksip used as registrator and also proxy.
the registration to nksip server  is ok.
the register message's contact field is just like
Contact: <sip:alice@df7jal23ls0d.invalid;transport=ws>
     ;reg-id=1
     ;+sip.instance="<urn:uuid:f81-7dec-14a06cf1>"

when A invite B, the nk_register:find will return  the registered contact address that can't work (host will be XXXX.invalid). we can use reg_contact record 's  nkport to patch this. but when  the Invite message‘s  ACK message returns, the ACK's request  line's UserName and Domain will be Contact's record,and nk_resigter:find will return  empty.

the tricky solution is to use nk_register:get_all   and search for the right tcp address and port.
the get_all will return an array like below:
```erlang
    % {armejl7,{sip,<<"aliceQ8wdGvtPgwPDjwFMPyfv8QnzMMZrJIur">>,<<"dev.com.cn">>},
    % 	  [{reg_contact,
    % 		   {sip,ws,<<"o4qjt1bm">>,<<"kscovdpk9644.invalid">>,80},
    % 		   {uri,sip,<<"o4qjt1bm">>,<<>>,
    % 			   <<"kscovdpk9644.invalid">>,0,<<>>,
    % 			   [{<<"transport">>,<<"ws">>}],
    % 			   [],
    % 			   [<<"+sip.ice">>,
    % 				{<<"reg-id">>,<<"1">>},
    % 				{<<"+sip.instance">>,
    % 				 <<"\"<urn:uuid:8d880923-9185-44d1-acdd-76447fd590b4>\"">>},
    % 				{<<"expires">>,<<"600">>}],
    % 			   [],<<>>},
    % 		   1466146473713000,1466147073,1.0,
    % 		   <<"0g88hb601851ghie72q9k8">>,1,
    % 		   {nkport,
    % 			   {nksip,armejl7},
    % 			   nksip_protocol,wss,
    % 			   {0,0,0,0},
    % 			   10001,
    % 			   {10,17,41,13},
    % 			   56987,
    % 			   {0,0,0,0},
    % 			   10001,<0.413.0>,<0.412.0>,
    % 			   #{ws_proto => <<"sip">>}},
    % 		   [],[]}]}
```
the real port and wss will be used to fill the uri ,{proxy,uri} will make the message to be routed correctly,but the whole step is ugly,isn't it?
is there any formal solution to solve this webrtc client's bad contact address question?
```erlang
sip_route(Scheme, User, Domain, Req, _Call) ->
    {ok,SrvId}=nksip_request:srv_id(Req),
    {ok,Method}=nksip_request:meta(method,Req),
    io:format("sip_route scheme ~p user ~p domain ~p method ~p~n",
        [Scheme, User, Domain,Method]),
    %io:format("sip_route Req:[~p]~n",[Req]),
    if
        Method =:= 'REGISTER' ->
            process;
        true ->
            io:format("not register, find ~p ~p ~p~n",[Scheme, User,Domain]),
            Trans=lists:foldr(
                fun( X ,Acc)->
                    { _ ,{XScheme,XUser,XDomain},[#reg_contact{
                        contact=#uri{scheme=YScheme,user=YUser,domain=YDomain}
                        ,nkport=NkPort}|_]} = X,
                    if
                        XScheme=:=Scheme andalso XUser=:=User andalso XDomain=:=Domain->
                            Acc++[ { {XScheme,XUser,XDomain},NkPort}];
                        Scheme=:=YScheme andalso YUser=:=User andalso YDomain=:=Domain->
                            Acc++[{ {XScheme,XUser,XDomain},NkPort}];
                        true->
                            Acc
                    end
                end,[],nksip_registrar_util:get_all()),
            if
                length(Trans)>0 ->
                    { {ZScheme,ZUser,ZDomain},
                        #nkport{remote_ip=RemoteIp,remote_port=RemotePort,transp=Transp}}=
                            lists:nth(1,Trans),
                    Uri=#uri{ scheme=ZScheme ,user=ZUser,
                        domain =ZDomain , port = RemotePort,
                        opts = [{<<"transport">>,
                            list_to_binary(atom_to_list(Transp))}]  },
                    %list_to_binary(inet:ntoa(RemoteIp))
                    io:format("last Uri  ~p~n",[Uri]),
                    {proxy,Uri};
                true ->{reply, temporarily_unavailable}
            end
    end.
```

**Comment by kalta** [comment]
Sending invalid contact addresses for SIP WebRTC is common, because you cannot 'start' a SIP WebRTC call to a browser usually, it is not 'listening'.

How do you plan to call to the browser?

**Comment by matlab2000** [comment]
> How do you plan to call to the browser?

from a webrtc client(chrome,firefox etc),we can send an invite message. 
if the webrtc client A  want to be a callee, it must **register itself first.** 
1)  A--> nksip(as registrator) ,this scene has been described in this post。thanks to the nkport record,the message can follow the wss connection and reach  the webrtc client.
2) A-->nksip(as proxy)-->registrator,    this situation is much harder to deal with. the nksip  maybe need to change the REGISTER message's contact field to nksip's own  address, and also record something(the username and the wss connection pair).  when the other party call the webrtc , the invite message will be sent to nksip , the nksip check the request line and look up  (username, connection) pair , if any item matched ,  follow  the wss connection and reach the webrtc client A. 

thanks to the nksip's nice architecture, i think it will be ok to deal with those things.
