### ISSUE TITLE
Tutorial seems broken

### ISSUE THREAD

**Issue by ogolosovskiy** [NetComposer/nksip#67]
Hello Carlos González,

Thank you for your project.

I have installed nksip from scratch.
Ubuntu 16.04 LTS
Branch develop
commit b20f161dfaaaec34189fbbc99e9db59c23ec3ab8

I go through the https://github.com/NetComposer/nksip/blob/master/doc/guide/tutorial.md

ogo@ubuntu64:~/src/nksip$ make tutorial
...
erl -config samples/nksip_tutorial/priv/app.config \
	-args_file samples/nksip_tutorial/priv/vm.args 
Erlang/OTP 17 [erts-6.4] [source] [64-bit] [smp:8:8] [async-threads:10] [kernel-poll:false]

Eshell V6.4  (abort with ^G)
(nksip_tutorial@127.0.0.1)1> nksip:start(server, #{
(nksip_tutorial@127.0.0.1)1>         sip_local_host => "localhost",
(nksip_tutorial@127.0.0.1)1>         callback => nksip_tutorial_server_callbacks,
(nksip_tutorial@127.0.0.1)1>         plugins => [nksip_registrar],
(nksip_tutorial@127.0.0.1)1>         transports => "sip:all:5060, <sip:all:5061;transport=tls>"
(nksip_tutorial@127.0.0.1)1>     }).
{ok,armejl7}
(nksip_tutorial@127.0.0.1)2> nksip:start(client1, #{
(nksip_tutorial@127.0.0.1)2>         sip_local_host => "localhost",
(nksip_tutorial@127.0.0.1)2>         sip_from => "sip:client1@nksip",
(nksip_tutorial@127.0.0.1)2>         callback => nksip_tutorial_client_callbacks,
(nksip_tutorial@127.0.0.1)2>         plugins => [nksip_uac_auto_auth],
(nksip_tutorial@127.0.0.1)2>         transports => "sip:127.0.0.1:5070, sips:127.0.0.1:5071"
(nksip_tutorial@127.0.0.1)2>     }).
14:22:20.502 [warning] lager_error_logger_h dropped 49 messages in the last second that exceeded the limit of 50 messages/sec
14:22:20.502 [notice] gen_tcp port 5060 is in use, waiting (5)
14:22:21.503 [notice] gen_tcp port 5060 is in use, waiting (4)
14:22:22.504 [notice] gen_tcp port 5060 is in use, waiting (3)
14:22:23.505 [notice] gen_tcp port 5060 is in use, waiting (2)
14:22:24.506 [notice] gen_tcp port 5060 is in use, waiting (1)
{error,{transport_error,{could_not_start,{udp,could_not_open_tcp}}}}
(nksip_tutorial@127.0.0.1)3> 14:22:25.507 [error] could not start tcp transport on {0,0,0,0}:5060 (eaddrinuse)
14:22:25.507 [warning] UDP transport could not open TCP port 5060: eaddrinuse
14:22:25.507 [error] could not start UDP transport on {0,0,0,0}:0 (could_not_open_tcp)
14:22:25.507 [error] CRASH REPORT Process <0.286.0> with 0 neighbours exited with reason: eaddrinuse in gen_server:init_it/6 line 322
14:22:25.508 [error] CRASH REPORT Process <0.285.0> with 0 neighbours exited with reason: could_not_open_tcp in gen_server:init_it/6 line 322
14:22:25.508 [error] CRASH REPORT Process <0.284.0> with 0 neighbours exited with reason: {transport_error,{could_not_start,{udp,could_not_open_tcp}}} in gen_server:init_it/6 line 322
14:22:25.509 [error] Supervisor {<0.282.0>,nkservice_srv_sup} had child server started with nkservice_srv:start_link(#{callback => nksip_tutorial_client_callbacks,class => nksip,config => #{sip_from => {uri,sip,...},...},...}) at undefined exit with reason {transport_error,{could_not_start,{udp,could_not_open_tcp}}} in context start_error

Why client starts on 5060, instead 5070?

**Comment by ogolosovskiy** [comment]
all:5070 works. Please fix the tutorial.

**Comment by kalta** [comment]
Thanks,  I will fix it ASAP.
