### ISSUE TITLE
loadtests broken

### ISSUE THREAD

**Issue by ogolosovskiy** [NetComposer/nksip#68]
nksip develop https://github.com/NetComposer/nksip/issues/new

make loadtest - broken, can't start the service due the sip_listen format problem
nksip_loadtest:full() - multiple problems, looks like can't start due the port sharing problems

**Comment by kalta** [comment]
What branch are you using? Last tagged version should work ok

**Comment by ogolosovskiy** [comment]
Just last develop. Commit 6c4cf0a0fa571ada44545cd58ac0de2b7d914818
Which tag do you recommend?
Your last tag was Jul 25, 2014. Too far :(

**Comment by kalta** [comment]
Yes, but you should use that if you are not going to dig into the code. 
There are no important bugs reported since that far.

**Comment by kalta** [comment]
Version v0.5.0 just tagged, everything is updated and all tests should be passing
