### ISSUE TITLE
Merge/Rebase ng into develop

### ISSUE THREAD

**Issue by edescourtis** [NetComposer/nksip#69]
Is there a plan on adding rebar3 support to the develop branch?

**Comment by kalta** [comment]
Yes, when I have some time

Carlos Gonzalez
Founder

ErlNETS Technologies SL
Navarro Ledesma 134, 29010 Malaga, Spain
+34674186274

**Comment by edescourtis** [comment]
Do you need any help with this project? I have been working with SIP and Erlang for the last 8 years.

**Comment by kalta** [comment]
Sure, anything you can do towards making it rebar3-compatible (while passing tests) would be great.
I plan to work on that in the following weeks.

**Comment by edescourtis** [comment]
I am guessing I should make the changes on the develop branch.

**Comment by kalta** [comment]
ng would be better... I plan to be there in a week or so

**Comment by kalta** [comment]
I just tagged v0.5.0 with all tests passing
I plan now to merge into ng a continue to R19/rebar3

**Comment by chunshengit** [comment]
Hi, Carlos: 
Is ng branch the updated branch with rebar integrated?
How do I proceed with the bugs/issues found in this branch?
I can't start the "make shell". 

nksip_app.erl: line 80: 
ServiceDefaults = nklib_util:extract(Parsed, ServiceKeys),
should be 
ServiceDefaults = nklib_util:extract(maps:to_list(Parsed), ServiceKeys),
