### ISSUE TITLE
B2BUA Support?

### ISSUE THREAD

**Issue by cystbear** [NetComposer/nksip#73]
Does NkSIP support B2BUA?
If no, any ideas about implementation or even any example?

**Comment by kalta** [comment]
Of course it does. Many of the samples and tests follow that pattern.

**Comment by cystbear** [comment]
**S** in `latency` stands for `speed`

**Comment by kalta** [comment]
Great comment, congratulations.

**Comment by cystbear** [comment]
@kalta there is no any kind of offence, joke no more
