### ISSUE TITLE
Is this project still alive ?

### ISSUE THREAD

**Issue by silviucpp** [NetComposer/nksip#78]
Hello,

Is this project still alive ? I saw some PR's without any feedback and not too much activity in the last year here.

Silviu

**Comment by kalta** [comment]
Hi. I'm the author.

I could not work on it for a while as you know.
It is however my understanding that it is being used successfully in a
number of production projects over the world.

Any case, I plan to resume working on it very soon with a brand new focus.

Carlos Gonzalez

**Comment by silviucpp** [comment]
Hello Carlos, 

Thanks for your feedback. Can you detail a bit what will be the new focus on the project ?

Silviu

**Comment by kalta** [comment]
I'm working on it right now. You can expect a new release in some days.

**Comment by silviucpp** [comment]
Hello Carlos, 

Your new release will fix compiling with rebar3 and otp 21 ?

Silviu

**Comment by kalta** [comment]
I'm afraid a more priority project came in.

I expect to come back to it is as soon as possible.

Yes, I had it already compiling with rebar3 and Erlang 21, however, many things were still not working, only basic OPTIONS was.
